!> Some collection of routines, for demonstrating documentation 
!! For doxygen, custom CSS usage can be specified in <ROOT>/Doxyfile

module routines
  use kinds, only: dp
  implicit none
  public

  !> @class DummyType
  !! @brief Dummy class, demoing Doxygen documentation syntax.
  !!
  !! ### Notes:
  !! * Markdown syntax is completely valid
  !! * Doxygen will infer public/private based on the declarations
  !! * However, it will get this wrong if the default behaviour is changed, i.e. one declares the class
  !!   attributes private by default
  !<
  type DummyType
     !> A private attribute will not be parsed by doyxgen
     integer, private :: a
     !> @public An example of public data
     real(dp), public :: b
     integer, public :: c   !< @public Another example of public data, with same-line doc
     !> @private Attributes tagged as private will also not be shown in the documentation
     integer :: d
     integer :: e   !< Assumed public
   contains
     procedure :: start => dummy_start  !< @copydoc routines::dummy_start
     final :: end                       !< @copydoc routines::end
  end type DummyType

contains

  !> @brief A dummy initialiser for the DummyType class.
  !!
  !! @param[in]  a  Some integer
  !! @param[in]  b  Some double
  !<
  subroutine dummy_start(this, a, b)
    class(DummyType), intent(inout) :: this
    integer, intent(in) :: a
    real(dp), intent(in) :: b
    this%a = a
    this%b = b
    this%c = a * b
  end subroutine dummy_start

  !>  @brief Finalize an instance of DummyType
  !!
  !! This also does more or less nothing
  !<
  subroutine end(this)
    type(DummyType), intent(inout) :: this
    this%a = 0
    this%b = 0.
  end subroutine end


  ! NOTE: Standard fortran comments are not parsed by Ford or Doxygen
  
  ! --------------------------------------
  ! Standard Ford Documentation Style
  ! --------------------------------------
  ! docmark = !!
  ! Documentation is placed beneath the code being documented
  ! i.e. the opposite from Doxygen.    
  ! General Markdown syntax is correctly parsed.    
  ! Latex is treated with MathJax.

  function norm(a) result(norm_of_a)
    !! Compute the norm of the vector \(\mathbf{a}\)  
    !! The norm of the vector is defined as:
    !! \[ |\mathbf{a}| = \sqrt{ \mathbf{a} \cdot \mathbf{a} } \]
    
    real(dp), intent(in) :: a(:)
    !! Vector a
    real(dp) :: norm_of_a
    !! norm of vector a
    
    norm_of_a = sqrt(dot_product(a, a))
  end function norm


  
  ! -----------------------------------------------------------------
  !  Ford Documentation Placement Above the Line
  ! -----------------------------------------------------------------
  ! * Available since Ford v1.0.0.
  ! * This is my preferred style, and offers most interoperability with Doxygen 
  !
  ! Documentation is placed above the code that's being documented.
  ! predocmark = !>
  ! This documentation can also be parsed by Doxygen.
  ! One is also able to add documentation after variables, on the same line.
  ! * See the declaration of distance_matrix, for example.

  
  !> Construct distance matrix. 
  !>                                                                                              
  !> Given a set of atomic positions, construct a distance matrix:
  !> 
  !> \[
  !>    d_{ij} = |\mathbf{r}_j - \mathbf{r}_i|,
  !> \]
  !> 
  !> where \(\mathbf{r}_i\) is the position of atom \(i\).
  !>
  !> For more information on distance matrix, one can look at
  !> [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance_matrix.html).  
  !> Markdown hyperlinks work for both Ford and Doxygen.
  !>
  !> Examples of tags:
  !> @note
  !>  This is an example of a note, generated by the note tag
  !> @endnote
  !> 
  !> @todo This is an example of a todo, generated by the todo tag.  
  !> All following text will be included with this tag unless
  !> the tag is closed or a new tag is opened.
  !>
  !> @warning This is an example of a warning, generated by the warning tag
  !> @endwarning
  !> 
  !> Back to normal text. note, todo and warning tags are also recognised
  !> by doxygen, however the closing tags are not
  
  function distance_matrix(positions) result(d)
    !> atomic positions 
    real(dp), intent(in) :: positions(:,:)
    real(dp), allocatable :: d(:,:)            !! distance matrix
    integer :: ia, ja, n_atoms
    
    n_atoms = size(positions, 2)
    allocate(d(n_atoms, n_atoms))
    
    do ia = 1, n_atoms
       do ja = ia, n_atoms
          d(ia, ja) = norm(positions(ja, :) - positions(ia, :))
          d(ja, ia) = d(ia, ja)
       enddo
    enddo
    
  end function distance_matrix


  
  ! -----------------------------------------------------------------
  ! Doxygen Documentation
  ! -----------------------------------------------------------------
  ! Ford does not recognise important Doxygen tags, such as @brief, @param
  ! and @return, however they still get parsed.
  ! 
  ! The start and end of equations also uses slightly different syntax
  ! => equations are not cross-compatible 
  ! Ford: \[ \]     Doxygen  \f[  \f]


  !> @brief Compute distance matrix.
  !!
  !! Given a set of atomic positions, construct a distance matrix:
  !!
  !! \f[
  !!    d_{ij} = |\mathbf{r}_j - \mathbf{r}_i|,
  !! \f]
  !!
  !! where \f$\mathbf{r}_i\f$ is the position of atom \f$i\f$.
  !!
  !! For more information on distance matrix, one can look at
  !! [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance_matrix.html).
  !! Markdown hyperlinks work for both Ford and Doxygen.
  !!
  !! Example code usage:
  !! \code{.f03}
  !!  d = distance_matrix_again(positions)
  !! \endcode
  !!
  !! Examples of tags parsed by doxygen:
  !! @note
  !!  This is an example of a note, generated by the note tag.
  !!
  !! @warning This is an example of a warning, generated by the warning tag, indicating some potential
  !!  issue with the routine.
  !!
  !! @param[in]  positions  atomic positions.
  !! @param[in]  dummy      An instance of \link DummyType DummyType \endlink, which does nothing.
  !! @return     d          distance_matrix.
  !<
  function distance_matrix_again(positions, dummy) result(d)
    real(dp), intent(in) :: positions(:,:)
    type(DummyType), optional, intent(in) :: dummy
    real(dp), allocatable :: d(:,:)

    ! Local variables are not parsed by doxygen, but it still may be worth documenting them
    integer :: n_atoms     ! Number of atoms
    integer :: ia, ja      ! Atomic indices

    n_atoms = size(positions, 2)
    allocate(d(n_atoms, n_atoms))
    
    do ia = 1, n_atoms
       do ja = ia, n_atoms
          d(ia, ja) = norm(positions(ja, :) - positions(ia, :))
          d(ja, ia) = d(ia, ja)
       enddo
    enddo
    
  end function distance_matrix_again

    ! USE ALL doxygen tags    https://dannyvanpoucke.be/oop-fortran-tut6-en/
    ! Inline documentation
    ! More complex maths
    ! Links to markdown
    ! Class documentation

  
end module routines
